version: "3.7"

services:
  database:
    container_name: flightai_database
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_NAME}
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    networks:
      - flightai
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    command: postgres -p ${POSTGRES_PORT} -c 'shared_buffers=128MB' -c 'max_connections=200'

  migrations:
    container_name: flightai_migrations
    restart: on-failure:3
    build:
      context: .
      dockerfile: migrations/Dockerfile
    env_file:
      - .env-dev
    environment:
      POSTGRES_HOST: flightai_database
    command: alembic upgrade head
    depends_on:
      - database
    networks:
      - flightai

  rabbitmq:
    container_name: flightai_rabbitmq
    image: "rabbitmq:3.9.17-management"
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS}
      RABBITMQ_ERLANG_COOKIE: ${ERLANG_COOKIE}
    ports:
      - "${RABBITMQ_PORT_API}:15672"
      - "${RABBITMQ_PORT_MAIN}:5672"
    networks:
      - flightai

networks:
  flightai:
    driver: bridge
