apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Release.Name }}-chat
  name: {{ .Release.Name }}-chat
spec:
  replicas: {{ .Values.chat.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-chat
  strategy: {}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
      labels:
        app: {{ .Release.Name }}-chat
    spec:
      containers:
        - name: {{ .Release.Name }}-chat
          image: "{{ .Values.chat.image.registry }}/{{ .Values.chat.image.repository }}:{{ .Values.chat.image.tag }}"
          resources:
            {{- toYaml .Values.chat.resources | nindent 12 }}
          envFrom:
            - secretRef:
                name: {{ .Values.secrets.secret_name }}
            - configMapRef:
                name: {{ .Release.Name }}-env
          imagePullPolicy: Always
          startupProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - "pidof -x python"
            periodSeconds: 1
            failureThreshold: 30
          livenessProbe:
            periodSeconds: 20
            failureThreshold: 3
            exec:
              command:
                - /bin/sh
                - -c
                - "pidof -x python"
      restartPolicy: Always
