import random

MOCK_ANSWERS = [
    {
        "What is your name?": "Kevin",
        "What is your age?": "35",
        "Which problems do you have related to sleep, if any?": "Excessive daytime sleepiness, Difficulty waking up or getting out of bed",
        "What have you used to improve your sleep?": "Supplements (e.g. melatonin), Changing surroundings (e.g. sleep mask, blackout curtains), "
        "Mindfulness and meditation, Exercise",
        "What is your typical bed time and wake-up time *on weekdays*?": "1 am - 8 am",
        "What is your typical bed time and wake-up time *on weekends*?": "2 am - 10 am",
        "During the past month, how long does it typically take you to fall asleep after going to bed (in min)?": "15",
        "How many hours of sleep do you typically get per night (in hours)?": "8",
        "Do you experience difficulty waking up in the morning, even after getting enough sleep?": "no",
        "Do you consider yourself a morning person or a night owl?": "Night Owl",
        "Do you need an alarm to wake up on most days? ": "yes",
        "How long after waking up does it typically take you to feel fully alert and focused? ": "30 min to 1h",
        "When do you feel most alert and productive?": "Evening",
        "When do you prefer engaging in mentally demanding activities (like analysis, writing, coding)?": "Morning, Evening",
    },
    {
        "What is your name?": "Shelley",
        "What is your age?": "72",
        "Which problems do you have related to sleep, if any?": "Difficulty falling asleep, Difficulty waking up or getting out of bed",
        "What have you used to improve your sleep?": "Supplements (e.g. melatonin), Exercise",
        "What is your typical bed time and wake-up time *on weekdays*?": "2am-11am",
        "What is your typical bed time and wake-up time *on weekends*?": "3am-12pm",
        "During the past month, how long does it typically take you to fall asleep after going to bed (in min)?": "20",
        "How many hours of sleep do you typically get per night (in hours)?": "6",
        "Do you experience difficulty waking up in the morning, even after getting enough sleep?": "yes",
        "Do you consider yourself a morning person or a night owl?": "Night Owl",
        "Do you need an alarm to wake up on most days? ": "yes",
        "How long after waking up does it typically take you to feel fully alert and focused? ": "30 min to 1h",
        "When do you feel most alert and productive?": "Evening",
        "When do you prefer engaging in mentally demanding activities (like analysis, writing, coding)?": "Evening",
    },
    {
        "What is your name?": "Ash",
        "What is your age?": "25",
        "Which problems do you have related to sleep, if any?": "Difficulty waking up or getting out of bed, Excessive daytime sleepiness, Difficulty staying asleep",
        "What have you used to improve your sleep?": "Prescription medication (e.g. trazodone, Ambien), Exercise, None",
        "What is your typical bed time and wake-up time *on weekdays*?": "10pm - 7am",
        "What is your typical bed time and wake-up time *on weekends*?": "2am - 12pm",
        "During the past month, how long does it typically take you to fall asleep after going to bed (in min)?": "35",
        "How many hours of sleep do you typically get per night (in hours)?": "7",
        "Do you experience difficulty waking up in the morning, even after getting enough sleep?": "yes",
        "Do you consider yourself a morning person or a night owl?": "I don't know",
        "Do you need an alarm to wake up on most days? ": "no",
        "How long after waking up does it typically take you to feel fully alert and focused? ": "Less than 30 min",
        "When do you feel most alert and productive?": "Morning",
        "When do you prefer engaging in mentally demanding activities (like analysis, writing, coding)?": "Afternoon",
    },
    {
        "What is your name?": "Niko",
        "What is your age?": "29",
        "Which problems do you have related to sleep, if any?": "Physical symptoms (e.g. headaches, pain), Difficulty falling asleep",
        "What have you used to improve your sleep?": "Changing surroundings (e.g. sleep mask, blackout curtains), Supplements (e.g. melatonin)",
        "What is your typical bed time and wake-up time *on weekdays*?": "01am-10pm",
        "What is your typical bed time and wake-up time *on weekends*?": "1am-10am",
        "During the past month, how long does it typically take you to fall asleep after going to bed (in min)?": "30",
        "How many hours of sleep do you typically get per night (in hours)?": "8",
        "Do you experience difficulty waking up in the morning, even after getting enough sleep?": "no",
        "Do you consider yourself a morning person or a night owl?": "afternoon person",
        "Do you need an alarm to wake up on most days? ": "yes",
        "How long after waking up does it typically take you to feel fully alert and focused? ": "30 min to 1h",
        "When do you feel most alert and productive?": "Afternoon",
        "When do you prefer engaging in mentally demanding activities (like analysis, writing, coding)?": "Evening",
    },
    {
        "What is your name?": "Megan",
        "What is your age?": "65",
        "Which problems do you have related to sleep, if any?": "Emotional symptoms (e.g. irritability, depression), Difficulty staying asleep, Difficulty falling asleep",
        "What have you used to improve your sleep?": "Prescription medication (e.g. trazodone, Ambien), Changing surroundings "
        "(e.g. sleep mask, blackout curtains)",
        "What is your typical bed time and wake-up time *on weekdays*?": "10 pm - 6 am",
        "What is your typical bed time and wake-up time *on weekends*?": "10 pm - 6 am",
        "During the past month, how long does it typically take you to fall asleep after going to bed (in min)?": "40",
        "How many hours of sleep do you typically get per night (in hours)?": "8",
        "Do you experience difficulty waking up in the morning, even after getting enough sleep?": "no",
        "Do you consider yourself a morning person or a night owl?": "Morning Person",
        "Do you need an alarm to wake up on most days? ": "no",
        "How long after waking up does it typically take you to feel fully alert and focused? ": "I don't know",
        "When do you feel most alert and productive?": "Morning",
        "When do you prefer engaging in mentally demanding activities (like analysis, writing, coding)?": "Morning",
    },
]


def get_user_answers(phone: str) -> dict:
    return random.choice(MOCK_ANSWERS)
